#version: '3.8'

services:
  db:
    image: mariadb:10.5
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build: ./backend
    image: python:3.10
    container_name: backend_dev
    working_dir: /app
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=mysql+pymysql://root:password@db:3306/userdb
    command: >
      bash -c "
      python -m venv venv &&
      source venv/bin/activate &&
      pip install --upgrade pip &&
      pip install -r requirements.txt &&
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "
    depends_on:
      - db
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    container_name: nginx_reverse_proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mariadb_data:
    driver: local
